# Generated by Django 5.1.4 on 2024-12-17 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comparison',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('prompt', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('comparison', models.TextField()),
                ('similarity', models.FloatField()),
                ('link', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comparison_prompt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='comparisons.comparison')),
            ],
        ),
    ]
